### ISSUE TITLE
Odd invisible links to feed.xml and main.css

### ISSUE THREAD

**Issue by tortoro** [TheDeepEnd/thedeepend.github.io#3]
There are two invisible links being generated in the header.html nav bar now. One for feed.xml and another for main.css, I'm not sure what happened but they were introduced in the most recent commit to master.
https://github.com/TheDeepEnd/thedeepend.github.io/commit/3f4e1d7f58058620c0c9a27e1bfbd209eec8d6aa

**Comment by enriquezm** [comment]
Also, sorted page listing to make it more intuitive.
